# -----------------------------------------------------------------------------
# Timing Constraints for Analogue Pocket
# -----------------------------------------------------------------------------

# 1. Primary Input Clocks
# 74.25 MHz main clocks from APF
create_clock -name clk_74a -period 13.468 [get_ports clk_74a]
create_clock -name clk_74b -period 13.468 [get_ports clk_74b]
# SPI clock for host bridge
create_clock -name bridge_spiclk -period 24.000 [get_ports bridge_spiclk]

# 2. Derive PLL Clocks
# This automatically creates generated clocks for all PLL outputs
derive_pll_clocks
derive_clock_uncertainty

# 3. User-Friendly Clock Aliasing & Grouping
# We use 'set_clock_groups' to tell Quartus that these domains are asynchronous.
# This significantly speeds up P&R by preventing unnecessary cross-domain analysis.

# Bridge/Client Domain (74.25MHz)
set bridge_clks [get_clocks {clk_74a clk_74b}]

# SDRAM Domain (133.33MHz)
# Identifies the output of mf_pllsdram
set sdram_clks  [get_clocks {ic|mp2|mf_pllsdram_inst|altera_pll_i|general[*].gpll~PLL_OUTPUT_COUNTER|divclk}]

# Video Domain (20MHz)
# Identifies the outputs of mf_pllbase
set video_clks  [get_clocks {ic|mp1|mf_pllbase_inst|altera_pll_i|general[*].gpll~PLL_OUTPUT_COUNTER|divclk}]

set_clock_groups -asynchronous \
    -group $bridge_clks \
    -group $sdram_clks \
    -group $video_clks

# 4. SDRAM Physical Interface Constraints
# The SDRAM clock is generated by a DDIO component (shifted 180 degrees)
# We constrain against this pin to accurately account for I/O routing delays.
create_generated_clock -name dram_clk_pin -source [get_pins -compatibility_mode *|sdramclk_ddr|*|ddio_outa[0]|dataout] [get_ports dram_clk]

# Physical Timings (Based on AS1C8M16PL-70BIN / AS4C32M16SB)
# data access delay (tAC)
set_input_delay -clock dram_clk_pin -max 6.4 [get_ports {dram_dq[*]}]
# data output hold time (tOH)
set_input_delay -clock dram_clk_pin -min 2.5 [get_ports {dram_dq[*]}]

# data input setup time (tIS)
set_output_delay -clock dram_clk_pin -max 1.5 [get_ports {dram_a[*] dram_ba[*] dram_dq[*] dram_ras_n dram_cas_n dram_we_n dram_dqm[*]}]
# data input hold time (tIH)
set_output_delay -clock dram_clk_pin -min -0.8 [get_ports {dram_a[*] dram_ba[*] dram_dq[*] dram_ras_n dram_cas_n dram_we_n dram_dqm[*]}]

# 5. Clock Domain Crossing (CDC) IP Constraints
# Tighten skew on Gray pointers to ensure reliable capture in the destination domain
set_max_skew -from [get_registers {*|async_fifo:*|wptr_gray_q[*]}] -to [get_registers {*|async_fifo:*|wptr_gray_sync_r1[*]}] 2.0
set_max_skew -from [get_registers {*|async_fifo:*|rptr_gray_q[*]}] -to [get_registers {*|async_fifo:*|rptr_gray_sync_w1[*]}] 2.0

# Prevent the fitter from placing CDC registers too far apart
set_net_delay -max -from [get_registers {*|async_fifo:*|wptr_gray_q[*]}] -to [get_registers {*|async_fifo:*|wptr_gray_sync_r1[*]}] 3.0
set_net_delay -max -from [get_registers {*|async_fifo:*|rptr_gray_q[*]}] -to [get_registers {*|async_fifo:*|rptr_gray_sync_w1[*]}] 3.0

# Cut the timing paths for Gray pointers (they are handled by synchronizers)
set_false_path -from [get_registers {*|async_fifo:*|wptr_gray_q[*]}] -to [get_registers {*|async_fifo:*|wptr_gray_sync_r1[*]}]
set_false_path -from [get_registers {*|async_fifo:*|rptr_gray_q[*]}] -to [get_registers {*|async_fifo:*|rptr_gray_sync_w1[*]}]

# False paths for 1-bit synchronizers (synch_3)
set_false_path -to [get_registers {*|synch_3:*|sreg[0]}]

# False paths for Ping-Pong Buffer (M10K Dual-Clock RAM)
# Data is written in clk_sys and read in clk_vid with vsync isolation.
set_false_path -from [get_registers {*|line_buffer:*|buffer_*}] -to [get_registers {*|line_buffer:*|pix_word_q*}]
